// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjfb-Aj8OZv4_QsrFMtn_mDRwH6DC8TEY',
    appId: '1:426256480277:web:bdc69568d4379fb827761c',
    messagingSenderId: '426256480277',
    projectId: 'bay-yahe-9f408',
    authDomain: 'bay-yahe-9f408.firebaseapp.com',
    databaseURL: 'https://bay-yahe-9f408-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bay-yahe-9f408.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxfj7kJ84evqltYvO4I_lbZi0bP9KqvA',
    appId: '1:426256480277:android:59f6591725477f8827761c',
    messagingSenderId: '426256480277',
    projectId: 'bay-yahe-9f408',
    databaseURL: 'https://bay-yahe-9f408-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bay-yahe-9f408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj4yysTFHXCL7qT7Sjt-n5q1X2984NddI',
    appId: '1:426256480277:ios:d7ae48b961404e3c27761c',
    messagingSenderId: '426256480277',
    projectId: 'bay-yahe-9f408',
    databaseURL: 'https://bay-yahe-9f408-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bay-yahe-9f408.appspot.com',
    androidClientId: '426256480277-1amli47m5qhl6pfl77mmrtlr0uka2ah0.apps.googleusercontent.com',
    iosClientId: '426256480277-6gvet31eds2qhcknci4bqt060kbo3i9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj4yysTFHXCL7qT7Sjt-n5q1X2984NddI',
    appId: '1:426256480277:ios:ba2683065d81f5e327761c',
    messagingSenderId: '426256480277',
    projectId: 'bay-yahe-9f408',
    databaseURL: 'https://bay-yahe-9f408-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bay-yahe-9f408.appspot.com',
    androidClientId: '426256480277-1amli47m5qhl6pfl77mmrtlr0uka2ah0.apps.googleusercontent.com',
    iosClientId: '426256480277-gbht3qevt1a75vscu54ntbrcf08bnera.apps.googleusercontent.com',
    iosBundleId: 'com.example.driver.RunnerTests',
  );
}
